# mise.toml

[tools]
rust = "latest"

"cargo:cargo-tarpaulin" = "latest"

[task_config]
includes = ["bin"]

[tasks.build]
run = 'cargo build'

[tasks.test]
description = "run unit tests"
run = "cargo test"

[tasks.coverage]
description = "generate test coverage report"
run = "cargo tarpaulin"
